version: '3.8'
services:
  frontend:
    build:
      context: ./workspace/frontend
    ports:
      - "3001:3001"
  backend:
    build:
      context: ./workspace/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PWD: 1234
      PG_NAME: mononews
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mononews
    ports: 
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local